FROM ubuntu:16.04

# Needed to install pyside2-tools without issues
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y \
        software-properties-common && \
    add-apt-repository -y ppa:thopiekar/pyside-git && \
    apt-get update && apt-get install -y \
        python \
        python-dev \
        python-pip \
        python-qt4 \
        python-pyqt5 \
        python-pyside \
        python-pyside2 \
        pyside2-tools \
        xvfb

# Make pyside2uic availble for Python 2.x
RUN cp -avr /usr/lib/python3/dist-packages/pyside2uic /usr/local/lib/python2.7/dist-packages

# Nose is the Python test-runner
RUN pip install nose nosepipe

# Enable additional output from Qt.py
ENV QT_VERBOSE true
ENV QT_TESTING true

# Xvfb
ENV DISPLAY :99

# Warnings are exceptions
ENV PYTHONWARNINGS="ignore"

WORKDIR /workspace/Qt.py
ENTRYPOINT cp -r /Qt.py /workspace && \
    Xvfb :99 -screen 0 1024x768x16 2>/dev/null & \
    while ! ps aux | grep -q '[0]:00 Xvfb :99 -screen 0 1024x768x16'; \
        do echo "Waiting for Xvfb..."; sleep 1; done && \
    echo "#\n# Testing implementation.." && \
        python -u run_tests.py && \
    echo "#\n# Testing caveats..\n#"  && \
        python build_caveats.py && \
        nosetests \
            --verbose \
            --with-doctest \
            --with-process-isolation \
            test_caveats.py && \
    echo "#\n# Testing membership..\n#" && \
        python build_membership.py && \
        nosetests \
            --verbose \
            test_membership.py && \
    echo "#\n# Testing examples..\n#" && \
        nosetests \
        --verbose \
        --with-process-isolation \
        --with-doctest \
        --exe \
            examples/*/*.py && \
    echo Done
