FROM ubuntu:16.04

# Needed to install pyside2-tools without issues
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y \
        software-properties-common && \
    add-apt-repository -y ppa:thopiekar/pyside-git && \
    apt-get update && apt-get install -y \
        python3 \
        python3-dev \
        python3-pip \
        python3-pyqt4 \
        python3-pyqt5 \
        python3-pyside \
        python3-pyside2 \
        pyside2-tools \
        xvfb

# Nose is the Python test-runner
RUN pip3 install nose nosepipe

# Enable additional output from Qt.py
ENV QT_VERBOSE true
ENV QT_TESTING true

# Xvfb
ENV DISPLAY :99

WORKDIR /workspace/Qt.py
ENTRYPOINT cp -r /Qt.py /workspace && \
    Xvfb :99 -screen 0 1024x768x16 2>/dev/null & \
    while ! ps aux | grep -q '[0]:00 Xvfb :99 -screen 0 1024x768x16'; \
        do echo "Waiting for Xvfb..."; sleep 1; done && \
    echo "#\n# Testing implementation.." && \
        python3 -u run_tests.py && \
    echo "#\n# Testing caveats..\n#"  && \
        python3 build_caveats.py && \
        nosetests \
            --verbose \
            --with-doctest \
            --with-process-isolation \
            test_caveats.py && \
    echo "#\n# Testing examples..\n#" && \
        nosetests \
        --verbose \
        --with-process-isolation \
        --with-doctest \
        --exe \
            examples/*/*.py && \
    echo Done
