FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
        software-properties-common && \
    add-apt-repository -y ppa:thopiekar/pyside-git && \
    apt-get update && apt-get install -y \
        python \
        python-dev \
        python-pip \
        python-qt4 \
        python-pyqt5 \
        python-pyside \
        python-pyside2

# Nose is the Python test-runner
RUN pip install nose nosepipe

# Enable additional output from Qt.py
ENV QT_VERBOSE true

WORKDIR /workspace/Qt.py
ENTRYPOINT cp -r /Qt.py /workspace && \
    python build_caveats_tests.py && \
    nosetests \
        --verbose \
        --with-process-isolation \
        --with-doctest \
        --exe 
