FROM centos:7.3.1611

# Devtoolset-4 (equivalent of Redhat DTS 4.1) provides GCC 5.3.1
# Building Qt5 from git: https://wiki.qt.io/Building_Qt_5_from_Git
# Qt5 requirements: http://doc.qt.io/qt-5/linux-requirements.html
# Qt Web Engine: http://doc.qt.io/qt-5/qtwebengine-platform-notes.html
#                https://wiki.qt.io/How_to_Try_QtWebEngine
# PySide2: https://wiki.qt.io/PySide2_GettingStarted

# Show available devtools-4 packages
# RUN yum list available devtoolset-4-\*

RUN yum install -y deltarpm && \
    yum update -y && \
    yum install -y \
        # Devtools requirements
        centos-release-scl \
        # cmake3 requirements
        epel-release && \
    yum install -y \
        # gcc 5.3.1 (via Devtools which is equivalent of RedHat DTS)
        devtoolset-4-gcc*-5.3.1 \
        # glibc 2.17
        glibc-*-2.17 \
        # Qt5 requirements
        libXrender* libxcb* xcb* fontconfig* freetype* libXi* libXext* libX11* libSM* libICE* libglib* libpthread* gstreamer* \
        # QtWebEngine requirements
        bison* flex* gperf* libicu-devel libxslt-devel ruby \
        libgcrypt-devel libgcrypt pciutils-devel nss-devel libXtst-devel gperf cups-devel pulseaudio-libs-devel libgudev1-devel systemd-devel libcap-devel alsa-lib-devel flex bison ruby gcc-c++ dbus libXrandr-devel libXcomposite-devel libXcursor-devel dbus-devel fontconfig-devel \
        # Python requirements
        zlib-dev openssl-devel sqlite-devel bzip2-devel readline-devel tk-devel \
        valgrind-devel \
        # PySide2 requirements
        libxslt libxml2 libxml2-devel libxslt-devel cmake3 openssl* \
        # PySide
        python-pyside \
        # Xvfb etc
        Xvfb \
        mesa-dri-drivers \
        libxkbcommon \
        libxkbcommon-devel \
        libxkbcommon-x11 \
        libxkbcommon-x11-devel \
        # Various tools
        git wget

# RUN yum install -y xorg-x11-server-Xvfb

# Activate devtoolset-4 gcc 5.3.1
# RUN scl enable devtoolset-4 bash
ENV PATH="/opt/rh/devtoolset-4/root/usr/bin:${PATH}"

# Set workdir
WORKDIR /workdir

# Qt 5.6.1, Autodesk-modified
ENV QT_VER=5.6.1
RUN git clone --recursive --branch ${QT_VER} https://code.qt.io/qt/qt5.git && \
    rm -rf qt5/qtbase && \
    rm -rf qt5/qtx11extras && \
    git clone --recursive --branch adsk-contrib/vfx/${QT_VER} https://github.com/autodesk-forks/qtbase.git qt5/qtbase && \
    git clone --recursive --branch adsk-contrib/vfx/${QT_VER} https://github.com/autodesk-forks/qtx11extras.git qt5/qtx11extras && \
    cd qt5 && \
    ./configure -help && \
    ./configure -opensource -confirm-license -nomake examples -nomake tests && \
    make && \
    make install && \
    cd .. && rm -rf qt5

# Pip with nose
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    pip install -U pip && \
    pip install -U \
        nose \
        nosepipe \
        six && \
    rm -f get-pip.py

# PySide2
RUN git clone --recursive --branch 5.6 https://codereview.qt-project.org/pyside/pyside-setup && \
    pip install -U setuptools wheel six sphinx && \
    cd pyside-setup && \
    python setup.py \
        # bdist_wheel \
        install \
            --ignore-git \
            --qmake=/usr/local/Qt-${QT_VER}/bin/qmake \
            --cmake=/usr/bin/cmake3 \
            --openssl=/usr/bin/openssl && \
    # /usr/local/python/bin/pip2.7 install /workdir/pyside-setup/dist/*.whl
    cd .. && rm -rf pyside-setup
# Ugly fix to make PySide2 find the Qt libs
ENV LD_LIBRARY_PATH="/usr/local/Qt-5.6.1/lib:${LD_LIBRARY_PATH}"

# PyQt5
ENV SIP_VER=4.18
ENV PYQT_VER=5.6
RUN wget http://sourceforge.net/projects/pyqt/files/sip/sip-${SIP_VER}/sip-${SIP_VER}.tar.gz && \
    tar -xvf sip-${SIP_VER}.tar.gz && \
    cd sip-${SIP_VER} && \
    python configure.py && \
    make && \
    make install && \
    wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-${PYQT_VER}/PyQt5_gpl-${PYQT_VER}.tar.gz && \
    tar -xvf PyQt5_gpl-${PYQT_VER}.tar.gz && \
    cd PyQt5_gpl-${PYQT_VER} && \
    python configure.py \
        --verbose \
        --confirm-license \
        --qmake=/usr/local/Qt-${QT_VER}/bin/qmake && \
    make && \
    make install && \
    cd .. && rm -rf PyQt5_gpl-${PYQT_VER}

# PyQt4
# The specific PyQt4 version needs to be compatible with the same SIP used by PyQt5 (in this case SIP 4.18)
ENV PYQT4_VER=4.11.4
RUN wget http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-${PYQT4_VER}/PyQt-x11-gpl-${PYQT4_VER}.tar.gz && \
    tar -xvf PyQt-x11-gpl-${PYQT4_VER}.tar.gz && \
    cd PyQt-x11-gpl-${PYQT4_VER} && \
    python configure.py \
        # --verbose \
        --confirm-license \
        --qmake=/usr/local/Qt-${QT_VER}/bin/qmake && \
    make && \
    make install && \
    cd .. && rm -rf PyQt-x11-gpl-${PYQT4_VER}
