FROM fredrikaverpil/qtpytest3.4

RUN yum update -y

# Enable additional output from Qt.py
ENV QT_VERBOSE true
ENV QT_TESTING true

# Xvfb
ENV DISPLAY :99

# Prevent error: "Qt: Failed to create XKB context!"
# https://lists.debian.org/debian-backports/2014/10/msg00061.html
ENV QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb

# Warnings are exceptions
ENV PYTHONWARNINGS="ignore"

WORKDIR /workspace/Qt.py

ENTRYPOINT cp -r /Qt.py /workspace && \
    Xvfb :99 -screen 0 1024x768x16 2>/dev/null & \
    while ! ps aux | grep -q '[0]:00 Xvfb :99 -screen 0 1024x768x16'; \
        do echo "Waiting for Xvfb..."; sleep 1; done && \
    echo "#\n# Testing implementation.." && \
        python -u run_tests.py && \
    echo "#\n# Testing caveats..\n#"  && \
        python build_caveats.py && \
        nosetests \
            --verbose \
            --with-doctest \
            --with-process-isolation \
            test_caveats.py && \
    echo "#\n# Testing membership..\n#" && \
        python build_membership.py && \
        nosetests \
            --verbose \
            test_membership.py && \
    echo "#\n# Testing examples..\n#" && \
        nosetests \
        --verbose \
        --with-process-isolation \
        --with-doctest \
        --exe \
            examples/*/*.py && \
    echo Done
