FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
        software-properties-common && \
    add-apt-repository -y ppa:thopiekar/pyside-git && \
    apt-get update && apt-get install -y \
        python3 \
        python3-dev \
        python3-pip \
        python3-pyqt4 \
        python3-pyqt5 \
        python3-pyside \
        python3-pyside2

# Nose is the Python test-runner
RUN pip3 install nose nosepipe

# Enable additional output from Qt.py
ENV QT_VERBOSE true

WORKDIR /workspace/Qt.py
ENTRYPOINT cp -r /Qt.py /workspace && \
    python3 build_caveats_tests.py && \
    nosetests \
        --verbose \
        --with-process-isolation \
        --with-doctest \
        --exe 
